version: "3.8"

services:

    tax-calculator:
         container_name: tax-calculator
         image: thedoomx/tax-calculator-service
         build:
             context: ./
             dockerfile: ./Startup/Dockerfile
         ports: 
             - "5002:80"
         restart: on-failure
         networks: 
             - tax-calculator-network

networks:
    tax-calculator-network:
