apiVersion: v1
kind: Service
metadata:
  name: tax-calculator-service
spec:
  type: LoadBalancer
  ports:
  - port: 5002
    targetPort: 80
  selector:
    web-service: tax-calculator

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tax-calculator-service
spec:
  selector:
    matchLabels:
      web-service: tax-calculator
  template:
    metadata:
      labels:
        web-service: tax-calculator
        system: server
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                web-service: tax-calculator
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: tax-calculator-service
        image: thedoomx/tax-calculator-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
            
            
---

apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: tax-calculator-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tax-calculator
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10